Add mkbranch and setup_git_package

diff --git a/roles/distgit/files/mkbranch b/roles/distgit/files/mkbranch
--- a/roles/distgit/files/mkbranch
+++ b/roles/distgit/files/mkbranch
@@ -10,7 +10,7 @@
 
 # Figure out the environment we're running in
 RUNDIR=$(cd $(dirname $0) && pwd)
-GITROOT=/srv/git/repositories
+GITROOT=/srv/git/repositories/${GITTREE:-free}/rpms
 
 # check if a moron is driving me
 if [ ! -d $GITROOT ] ; then
@@ -30,7 +30,7 @@ IGNORE=
 BRANCH=""
 PACKAGES=""
 SRC_BRANCH="master"
-AUTHOR="Fedora Release Engineering <rel-eng@lists.fedoraproject.org>"
+AUTHOR="RPM Fusion Release Engineering <sysadmin@lists.rpmfusion.org>"
 
 Usage() {
     cat <<EOF
@@ -41,46 +41,53 @@ Usage:
     The /master suffix on branch names is assumed.
 
 Options:
-    -n,--test           Don't do nothing, only test
-    -i,--ignore         Ignore erroneous modules
-    -h,--help           This help message
-    -v,--verbose        Increase verbosity
+    -s,--source=<src_branch>	Use <src_branch> as the source branch.
+				Defaults is master
+                                /master suffix on other branches assumed
+    -n,--test			Don't do nothing, only test
+    -i,--ignore                 Ignore erroneous modules
+    -h,--help			This help message
+    -v,--verbose		Increase verbosity
 EOF
 }
 
 # parse the arguments
 while [ -n "$1" ] ; do
     case "$1" in
-    -h | --help )
-        Usage
-        exit 0
-        ;;
+	-h | --help )
+	    Usage
+	    exit 0
+	    ;;
 
-    -v | --verbose )
-        VERBOSE=$(($VERBOSE + 1))
-        ;;
+	-v | --verbose )
+	    VERBOSE=$(($VERBOSE + 1))
+	    ;;
 
-    -i | --ignore )
-        IGNORE="yes"
-        ;;
+	-i | --ignore )
+	    IGNORE="yes"
+	    ;;
 
-    -n | --test )
-        TEST="yes"
-        ;;
+	-n | --test )
+	    TEST="yes"
+	    ;;
 
+	-s | --source )
+	    shift
+	    SRC_BRANCH=$1
+	    ;;
 
-    -b | --branch )
-        shift
-        BRANCH=$1/master
-        ;;
+	-b | --branch )
+	    shift
+	    BRANCH=$1/master
+	    ;;
 
-    * )
-        if [ -z "$BRANCH" ] ; then
-        BRANCH="$1"
-        else
-        PACKAGES="$PACKAGES $1"
-        fi
-        ;;
+	* )
+	    if [ -z "$BRANCH" ] ; then
+		BRANCH="$1"
+	    else
+		PACKAGES="$PACKAGES $1"
+	    fi
+	    ;;
     esac
     shift
 done
@@ -91,19 +98,29 @@ if [ -z "$BRANCH" -o -z "$PACKAGES" ] ; then
     exit -1
 fi
 
+# Translate the source branch
+if [ $SRC_BRANCH == 'master' ] ; then
+    echo > /dev/null
+else
+    $SRC_BRANCH = $SRC_BRANCH/master
+fi
 
 # Sanity checks before we start doing damage
 NEWP=
 for p in $PACKAGES ; do
     [ $VERBOSE -gt 1 ] && echo "Checking package $p..."
     if [ ! -d $GITROOT/$p.git ] ; then
-    echo "ERROR: Package module $p is invalid" >&2
-    [ "$IGNORE" = "yes" ] && continue || exit -1
+	echo "ERROR: Package module $p is invalid" >&2
+	[ "$IGNORE" = "yes" ] && continue || exit -1
     fi
     $(GIT_DIR=$GITROOT/$p.git git rev-parse -q --verify \
+      $SRC_BRANCH >/dev/null) || \
+	(echo "ERROR: Invalid source branch '$SRC_BRANCH' for package $p" >&2; \
+	[ "$IGNORE" = "yes" ] && continue || exit -1)
+    $(GIT_DIR=$GITROOT/$p.git git rev-parse -q --verify \
       $BRANCH >/dev/null) && \
-    (echo "IGNORING: Package module $p already has a branch $BRANCH" >&2; \
-    [ "$IGNORE" = "yes" ] && continue || exit -1)
+	(echo "IGNORING: Package module $p already has a branch $BRANCH" >&2; \
+	[ "$IGNORE" = "yes" ] && continue || exit -1)
     NEWP="$NEWP $p"
 done
 PACKAGES="$(echo $NEWP)"
@@ -117,6 +134,14 @@ if [ -n "$TEST" ] ; then
     exit 0
 fi
 
+# This account must have the proper permissions as to not screw up the
+# repository work.
+if [ "$(id -un)" = "root" ] ; then
+    echo "Please run this script as yourself"
+    exit -3
+fi
+#### Change this to check for proper git-admin rights
+
 # "global" permissions check
 if [ ! -w $GITROOT ] ; then
     echo "ERROR: You can not write to $GITROOT"
@@ -129,7 +154,7 @@ fi
 # For every module, "create" the branch
 for NAME in $PACKAGES ; do
     echo
-    echo "Creating new module branch '$BRANCH' for '$NAME'..."
+    echo "Creating new module branch '$BRANCH' for '$NAME' from branch '$SRC_BRANCH'..."
 
     # permissions checks for this particular module
     if [ ! -w $GITROOT/$NAME.git/refs/heads/  ] ; then
@@ -141,16 +166,16 @@ for NAME in $PACKAGES ; do
     #[ $VERBOSE -gt 0 ] && echo "Creating $BRANCH-split tag for $NAME/$SRC_BRANCH..."
     # Is the above needed?
     #cvs -Q rtag -f "$BRANCH-split" $TOPLEVEL/$NAME/$SRC_BRANCH || {
-    #echo "ERROR: Branch split tag for $NAME/$SRC_BRANCH could not be created" >&2
-    #exit -2
+	#echo "ERROR: Branch split tag for $NAME/$SRC_BRANCH could not be created" >&2
+	#exit -2
     #}
-    [ $VERBOSE -gt 0 ] && echo "Creating $NAME $BRANCH from $NAME ..."
+    [ $VERBOSE -gt 0 ] && echo "Creating $NAME $BRANCH from $NAME $SRC_BRANCH..."
     $(pushd $GITROOT/$NAME.git >/dev/null && \
-    git branch --no-track $BRANCH `git rev-list --max-parents=0 master | head -1` && \
+    git branch --no-track $BRANCH $SRC_BRANCH && \
     popd >/dev/null) || {
-    echo "ERROR: Branch $NAME $BRANCH could not be created" >&2
+	echo "ERROR: Branch $NAME $BRANCH could not be created" >&2
         popd >/dev/null
-    exit -2
+	exit -2
     }
 done
 
